export type Language = "en" | "ar";

export const getLanguage = (): Language => {
  const stored = localStorage.getItem("language");
  return (stored as Language) || "en";
};

export const setLanguage = (lang: Language) => {
  localStorage.setItem("language", lang);
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
};

export const translations = {
  en: {
    // Home
    "home.title": "Connect Farms to Markets",
    "home.subtitle": "Bridge the gap between farmers and traders with intelligent market analysis and pre-planting coordination. Reduce waste, increase profits.",
    "home.getStarted": "Get Started",
    "home.learnMore": "Learn More",
    "home.platformFeatures": "Platform Features",
    "home.featuresDesc": "A complete solution for farmers and traders to make informed decisions",
    "home.forFarmers": "For Farmers",
    "home.forTraders": "For Traders",
    "home.marketAnalysis": "Market Analysis",
    "home.prePlantingMatch": "Pre-Planting Match",
    "home.smartPlanting": "Smart planting recommendations",
    "home.riskAssessment": "Risk assessment",
    "home.marketForecasts": "Market forecasts",
    "home.pdfReports": "PDF reports",
    "home.demandManagement": "Demand management",
    "home.supplyAlerts": "Supply alerts",
    "home.marketIntelligence": "Market intelligence",
    "home.priceInsights": "Price insights",
    "home.supplyVsDemand": "Supply vs demand",
    "home.priceIndicators": "Price indicators",
    "home.shortageDetection": "Shortage detection",
    "home.seasonalTrends": "Seasonal trends",
    "home.findTradingPartners": "Find trading partners",
    "home.reduceUncertainty": "Reduce uncertainty",
    "home.planProduction": "Plan production",
    "home.minimizeWaste": "Minimize waste",
    "home.howItWorks": "How It Works",
    "home.createAccount": "Create Account",
    "home.registerProfile": "Register as a farmer or trader and set up your profile with basic information",
    "home.submitData": "Submit Data",
    "home.enterDetails": "Enter your farm details or market demands and get instant analysis",
    "home.makeDecisions": "Make Decisions",
    "home.viewInsights": "View insights, market matches, and download recommendations to plan better",
    "home.readyTransform": "Ready to Transform Agriculture?",
    "home.joinPlatform": "Join farmers and traders across the region connecting supply and demand with confidence",
    "home.startFree": "Start for Free",

    // Navigation
    "nav.home": "Home",
    "nav.login": "Login",
    "nav.register": "Register",
    "nav.logout": "Logout",
    "nav.welcome": "Welcome",
    "nav.about": "About Us",
    "nav.contact": "Contact Us",

    // Auth Pages
    "auth.welcomeBack": "Welcome Back",
    "auth.signInDesc": "Sign in to your account to continue",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.noAccount": "Don't have an account?",
    "auth.registerHere": "Register here",
    "auth.createAccount": "Create Account",
    "auth.whatAreYou": "What describes you best?",
    "auth.fullName": "Full Name",
    "auth.phone": "Phone",
    "auth.region": "Region",
    "auth.required": "Required",
    "auth.alreadyAccount": "Already have an account?",
    "auth.loginHere": "Login here",
    "auth.demoAccounts": "Demo Accounts:",
    "auth.farmer": "Farmer",
    "auth.trader": "Trader",
    "auth.backRole": "Back to role selection",
    "auth.registerAs": "Register as",
    "auth.fillDetails": "Fill in your details to get started",

    // Farmer Dashboard
    "farmer.dashboard": "Farm Dashboard",
    "farmer.manage": "Manage your farm data and get recommendations",
    "farmer.totalFarms": "Total Farms",
    "farmer.region": "Region",
    "farmer.memberSince": "Member Since",
    "farmer.myFarms": "My Farms",
    "farmer.addFarm": "Add Farm",
    "farmer.addNewFarm": "Add New Farm",
    "farmer.crop": "Crop",
    "farmer.selectCrop": "Select crop",
    "farmer.area": "Area (hectares)",
    "farmer.enterArea": "Enter area",
    "farmer.season": "Season",
    "farmer.selectSeason": "Select season",
    "farmer.noFarms": "No farms yet",
    "farmer.addFirstFarm": "Add your first farm to get recommendations",
    "farmer.recommendation": "Recommendation",
    "farmer.selectFarm": "Select a farm to view recommendations",
    "farmer.riskLevel": "Risk Level",
    "farmer.recommended": "Recommended Crops",
    "farmer.avoid": "Avoid Planting",
    "farmer.downloadReport": "Download Report",

    // Trader Dashboard
    "trader.dashboard": "Trading Dashboard",
    "trader.manage": "Manage demand and monitor market supply",
    "trader.totalDemand": "Total Demand",
    "trader.units": "units tracked",
    "trader.activeProducts": "Active Products",
    "trader.inDemand": "in demand list",
    "trader.myDemands": "My Demands",
    "trader.addDemand": "Add Demand",
    "trader.addMarketDemand": "Add Market Demand",
    "trader.product": "Product",
    "trader.selectProduct": "Select product",
    "trader.quantity": "Expected Quantity",
    "trader.enterQuantity": "Enter quantity",
    "trader.period": "Time Period",
    "trader.selectPeriod": "Select period",
    "trader.noDemands": "No demands yet",
    "trader.addDemandFirst": "Add your market demands to track supply",
    "trader.marketSupply": "Market Supply",

    // Common
    "common.loading": "Loading...",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.approve": "Approve",
    "common.reject": "Reject",
    "common.download": "Download",
    "common.addFarm": "Add Farm",
    "common.addDemand": "Add Demand",

    // About Page
    "about.title": "About Agrivers",
    "about.subtitle": "Transforming agriculture through intelligent market connections and data-driven insights",
    "about.mission": "Our Mission",
    "about.missionDesc": "Agrivers bridges the gap between farmers and traders by providing intelligent market analysis tools and pre-planting coordination systems. We empower agricultural stakeholders with data and insights to make better decisions.",
    "about.missionDesc2": "Our platform reduces waste, increases profitability, and creates sustainable connections throughout the agricultural supply chain.",
    "about.vision": "Our Values",
    "about.sustainability": "Sustainability",
    "about.sustainabilityDesc": "We believe in promoting environmentally responsible farming practices that benefit both farmers and future generations.",
    "about.innovation": "Innovation",
    "about.innovationDesc": "Cutting-edge technology and data science drive our solutions to solve real agricultural challenges.",
    "about.community": "Community",
    "about.communityDesc": "We build a trusted community where farmers, traders, and stakeholders collaborate for mutual success.",
    "about.team": "Join Our Team",
    "about.teamDesc": "We're always looking for passionate individuals to help us transform agriculture. Contact us to learn about opportunities.",
    "about.joiningTeam": "We're growing and would love to hear from talented professionals interested in agriculture and technology",
    "about.readyJoin": "Ready to Join Us?",
    "about.joinDesc": "Start connecting your farm or business to the broader agricultural network today",
    "about.startNow": "Start Now",

    // Contact Page
    "contact.title": "Get In Touch",
    "contact.subtitle": "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.phoneAvailable": "Available during business hours",
    "contact.location": "Location",
    "contact.region": "Serving communities across the GCC region",
    "contact.sendMessage": "Send us a Message",
    "contact.namePlaceholder": "Your full name",
    "contact.emailPlaceholder": "your@email.com",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "What is this about?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.thankYou": "Thank You!",
    "contact.successMsg": "We've received your message and will get back to you shortly.",
    "contact.redirecting": "Redirecting you to the home page...",

    // Footer
    "footer.contact": "Contact",
  },
  ar: {
    // Home
    "home.title": "ربط المزارع بالأسواق",
    "home.subtitle": "سد الفجوة بين المزارعين والتجار من خلال تحليل السوق الذكي وتنسيق قبل الزراعة. قلل الهدر، وزد الأرباح.",
    "home.getStarted": "ابدأ الآن",
    "home.learnMore": "تعلم المزيد",
    "home.platformFeatures": "ميزات المنصة",
    "home.featuresDesc": "حل شامل للمزارعين والتجار لاتخاذ قرارات مستنيرة",
    "home.forFarmers": "للمزارعين",
    "home.forTraders": "للتجار",
    "home.marketAnalysis": "تحليل السوق",
    "home.prePlantingMatch": "مطابقة قبل الزراعة",
    "home.smartPlanting": "توصيات زراعية ذكية",
    "home.riskAssessment": "تقييم المخاطر",
    "home.marketForecasts": "توقعات السوق",
    "home.pdfReports": "تقارير PDF",
    "home.demandManagement": "إدارة الطلب",
    "home.supplyAlerts": "تنبيهات العرض",
    "home.marketIntelligence": "ذكاء السوق",
    "home.priceInsights": "رؤى الأسعار",
    "home.supplyVsDemand": "العرض مقابل الطلب",
    "home.priceIndicators": "مؤشرات الأسعار",
    "home.shortageDetection": "كشف النقص",
    "home.seasonalTrends": "الاتجاهات الموسمية",
    "home.findTradingPartners": "البحث عن شركاء تجاريين",
    "home.reduceUncertainty": "تقليل عدم اليقين",
    "home.planProduction": "تخطيط الإنتاج",
    "home.minimizeWaste": "تقليل الهدر",
    "home.howItWorks": "كيف يعمل",
    "home.createAccount": "إنشاء حساب",
    "home.registerProfile": "سجل كمزارع أو تاجر وأعد ملفك الشخصي بمعلومات أساسية",
    "home.submitData": "إرسال البيانات",
    "home.enterDetails": "أدخل تفاصيل مزرعتك أو احتياجاتك السوقية واحصل على التحليل الفوري",
    "home.makeDecisions": "اتخاذ القرارات",
    "home.viewInsights": "عرض الرؤى والمطابقات السوقية وتحميل التوصيات للتخطيط بشكل أفضل",
    "home.readyTransform": "هل أنت مستعد لتحويل الزراعة؟",
    "home.joinPlatform": "انضم إلى المزارعين والتجار عبر المنطقة للربط بين العرض والطلب بثقة",
    "home.startFree": "ابدأ مجانًا",

    // Navigation
    "nav.home": "الرئيسية",
    "nav.login": "تسجيل الدخول",
    "nav.register": "إنشاء حساب",
    "nav.logout": "تسجيل الخروج",
    "nav.welcome": "مرحبا",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",

    // Auth Pages
    "auth.welcomeBack": "أهلا وسهلا",
    "auth.signInDesc": "قم بتسجيل الدخول إلى حسابك للمتابعة",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signIn": "تسجيل الدخول",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.registerHere": "انقر هنا للتسجيل",
    "auth.createAccount": "إنشاء حساب",
    "auth.whatAreYou": "ما الذي يصفك بشكل أفضل؟",
    "auth.fullName": "الاسم الكامل",
    "auth.phone": "رقم الهاتف",
    "auth.region": "المنطقة",
    "auth.required": "مطلوب",
    "auth.alreadyAccount": "هل لديك حساب بالفعل؟",
    "auth.loginHere": "انقر هنا لتسجيل الدخول",
    "auth.demoAccounts": "حسابات توضيحية:",
    "auth.farmer": "مزارع",
    "auth.trader": "تاجر",
    "auth.backRole": "العودة لاختيار الدور",
    "auth.registerAs": "سجل كـ",
    "auth.fillDetails": "أدخل تفاصيلك للبدء",

    // Farmer Dashboard
    "farmer.dashboard": "لوحة المزرعة",
    "farmer.manage": "إدارة بيانات مزرعتك والحصول على التوصيات",
    "farmer.totalFarms": "إجمالي المزارع",
    "farmer.region": "المنطقة",
    "farmer.memberSince": "عضو منذ",
    "farmer.myFarms": "مزارعي",
    "farmer.addFarm": "إضافة مزرعة",
    "farmer.addNewFarm": "إضافة مزرعة جديدة",
    "farmer.crop": "المحصول",
    "farmer.selectCrop": "اختر المحصول",
    "farmer.area": "المساحة (هكتار)",
    "farmer.enterArea": "أدخل المساحة",
    "farmer.season": "الموسم",
    "farmer.selectSeason": "اختر الموسم",
    "farmer.noFarms": "لا توجد مزارع بعد",
    "farmer.addFirstFarm": "أضف مزرعتك الأولى للحصول على التوصيات",
    "farmer.recommendation": "التوصية",
    "farmer.selectFarm": "اختر مزرعة لعرض التوصيات",
    "farmer.riskLevel": "مستوى المخاطر",
    "farmer.recommended": "المحاصيل الموصى بها",
    "farmer.avoid": "تجنب الزراعة",
    "farmer.downloadReport": "تحميل التقرير",

    // Trader Dashboard
    "trader.dashboard": "لوحة التداول",
    "trader.manage": "إدارة الطلب ومراقبة العرض السوقي",
    "trader.totalDemand": "إجمالي الطلب",
    "trader.units": "الوحدات المتتبعة",
    "trader.activeProducts": "المنتجات النشطة",
    "trader.inDemand": "في قائمة الطلب",
    "trader.myDemands": "طلباتي",
    "trader.addDemand": "إضافة طلب",
    "trader.addMarketDemand": "إضافة طلب سوقي",
    "trader.product": "المنتج",
    "trader.selectProduct": "اختر المنتج",
    "trader.quantity": "الكمية المتوقعة",
    "trader.enterQuantity": "أدخل الكمية",
    "trader.period": "الفترة الزمنية",
    "trader.selectPeriod": "اختر الفترة",
    "trader.noDemands": "لا توجد طلبات بعد",
    "trader.addDemandFirst": "أضف طلباتك السوقية لتتبع العرض",
    "trader.marketSupply": "العرض السوقي",

    // Common
    "common.loading": "جاري التحميل...",
    "common.submit": "إرسال",
    "common.cancel": "إلغاء",
    "common.approve": "الموافقة",
    "common.reject": "الرفض",
    "common.download": "تحميل",
    "common.addFarm": "إضافة مزرعة",
    "common.addDemand": "إضافة طلب",

    // About Page
    "about.title": "عن أغريفرز",
    "about.subtitle": "تحويل الزراعة من خلال الاتصالات السوقية الذكية والرؤى المبنية على البيانات",
    "about.mission": "مهمتنا",
    "about.missionDesc": "تسد أغريفرز الفجوة بين المزارعين والتجار من خلال توفير أدوات تحليل السوق الذكية وأنظمة التنسيق قبل الزراعة. نحن نمكن أصحاب المصلحة الزراعيين بالبيانات والرؤى لاتخاذ قرارات أفضل.",
    "about.missionDesc2": "تقلل منصتنا الهدر وتزيد الربحية وتخلق اتصالات مستدامة في جميع سلسلة التوريد الزراعية.",
    "about.vision": "قيمنا",
    "about.sustainability": "الاستدامة",
    "about.sustainabilityDesc": "نؤمن بتعزيز الممارسات الزراعية المسؤولة بيئياً التي تفيد المزارعين والأجيال القادمة.",
    "about.innovation": "الابتكار",
    "about.innovationDesc": "تقنية متقدمة وعلوم البيانات تدفع حلولنا لحل التحديات الزراعية الحقيقية.",
    "about.community": "المجتمع",
    "about.communityDesc": "نحن نبني مجتمعاً موثوقاً حيث يتعاون المزارعون والتجار وأصحاب المصلحة لتحقيق النجاح المتبادل.",
    "about.team": "انضم إلى فريقنا",
    "about.teamDesc": "نحن نبحث دائماً عن أفراد متحمسين لمساعدتنا على تحويل الزراعة. تواصل معنا لمعرفة الفرص.",
    "about.joiningTeam": "نحن في مرحلة نمو ونود أن نسمع من محترفين موهوبين مهتمين بالزراعة والتكنولوجيا",
    "about.readyJoin": "هل أنت مستعد للانضمام إلينا؟",
    "about.joinDesc": "ابدأ بربط مزرعتك أو عملك بالشبكة الزراعية الأوسع اليوم",
    "about.startNow": "ابدأ الآن",

    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "نود أن نسمع منك. أرسل لنا رسالة وسنرد في أقرب وقت ممكن.",
    "contact.email": "البريد الإلكتروني",
    "contact.phone": "الهاتف",
    "contact.phoneAvailable": "متاح خلال ساعات العمل",
    "contact.location": "الموقع",
    "contact.region": "خدمة المجتمعات في منطقة دول مجلس التعاون الخليجي",
    "contact.sendMessage": "أرسل لنا رسالة",
    "contact.namePlaceholder": "اسمك الكامل",
    "contact.emailPlaceholder": "your@email.com",
    "contact.subject": "الموضوع",
    "contact.subjectPlaceholder": "عما تتحدث؟",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "أخبرنا المزيد عن استفسارك...",
    "contact.send": "إرسال الرسالة",
    "contact.thankYou": "شكراً لك!",
    "contact.successMsg": "لقد تلقينا رسالتك وسنرد عليك قريباً.",
    "contact.redirecting": "إعادة التوجيه إلى الصفحة الرئيسية...",

    // Footer
    "footer.contact": "اتصل",
  },
};

export const t = (key: string, lang: Language): string => {
  return (translations[lang] as any)[key] || key;
};
